openapi: 3.0.0
info:
  title: Locart Backend API
  version: 1.0.0
  description: API documentation for the Locart Server

servers:
  - url: http://localhost:8000
    description: Locart Server

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

paths:
  /api/v1/appointment:
    $ref: './appointment.yaml#/paths'
  /api/v1/auth:
    $ref: './auth.yaml#/paths'
  /api/v1/admin:
    $ref: './admin.yaml#/paths'
  /api/v1/amenities:
    $ref: './amenities.yaml#/paths'
  /api/v1/client:
    $ref: './client.yaml#/paths'
  /api/v1/dashboard:
    $ref: './dashboard.yaml#/paths'
  /api/v1/order:
    $ref: './order.yaml#/paths'
  /api/v1/product:
    $ref: './product.yaml#/paths'
  /api/v1/productcategory:
    $ref: './productcategory.yaml#/paths'
  /api/v1/role:
    $ref: './role.yaml#/paths'
  /api/v1/salons:
    $ref: './salons.yaml#/paths'
  /api/v1/service:
    $ref: './service.yaml#/paths'
  /api/v1/stylists:
    $ref: './stylists.yaml#/paths'